// <auto-generated />
namespace POS_APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CompanyEnity1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompanyEnity1));
        
        string IMigrationMetadata.Id
        {
            get { return "202102061238007_CompanyEnity1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
